### ISSUE TITLE
Fix license spec of transitive xmldom dependency

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-common#122]
ref: https://github.com/apache/cordova-coho/blob/master/docs/tools-release-process.md

When we do `coho check-license` to check the dependency licenses, we get the following message on `xmldom` at the end:

```sh
└─ known-issues
   ├─ manually-verified-versions
   │  └─ 0: xmldom@0.1.22
   ├─ license-key: not a compatible SPDX expression, and also used the plural 'licenses' as a key.
   ├─ pull-request-to-fix: https://github.com/jindw/xmldom/pull/178
   ├─ verified-license: (LGPL or MIT)
   └─ verified-license-notes: https://github.com/jindw/xmldom/blob/master/LICENSE . Note that the authors have omitted tags in their repo for their npm releases, but the hashes can be grabbed from 'npm info xmldom'
```

@shazron already got it fixed in jindw/xmldom#178 but they never did `npm publish` with the fix.

This `xmldom` issue affects all platform releases as well.

I hope we can get this fixed on `xmldom` in the near future.

**Comment by brodybits** [comment]
I just took over `xmldom` and published some updates that *should* resolve this warning message. I will check this the next time I publish an update.

**Comment by erisu** [comment]
I ran `check-license` and did not see xmldom listed anymore. Closing as resolved.
