### ISSUE TITLE
Error: Cannot find module '@netflix/nerror'

### ISSUE THREAD

**Issue by beevelop** [apache/cordova-common#149]
# Bug Report

## Problem
The exception below is being triggered reproducible with the most recent versions of Cordova.

### What is expected to happen?
Adding the iOS platform should work seamlessly for all plugins.

### What does actually happen?
```
Error: Cannot find module '@netflix/nerror'
Require stack:
- [...]/platforms/ios/cordova/node_modules/cordova-common/src/CordovaError.js
- [...]/platforms/ios/cordova/node_modules/cordova-common/cordova-common.js
- [...]/platforms/ios/cordova/lib/plugman/pluginHandlers.js
- [...]/platforms/ios/cordova/lib/projectFile.js
- [...]/platforms/ios/cordova/Api.js
- [...]/platforms/ios/cordova/version
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> ([...]/platforms/ios/cordova/node_modules/cordova-common/src/CordovaError.js:22:20)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[...]/platforms/ios/cordova/node_modules/cordova-common/src/CordovaError.js',
    '[...]/platforms/ios/cordova/node_modules/cordova-common/cordova-common.js',
    '[...]/platforms/ios/cordova/lib/plugman/pluginHandlers.js',
    '[...]/platforms/ios/cordova/lib/projectFile.js',
    '[...]/platforms/ios/cordova/Api.js',
    '[...]/platforms/ios/cordova/version'
  ]
}
```

### Command or Code
```bash
cordova platform add ios
```

### Versions & Environment
- macOS 10.14.6
- Node v14.4.0
- npm 6.14.5
- Cordova 9.0.0 (cordova-lib@9.0.1)
- cordova-ios@^6.0.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
Note for further investigation:
`@netflix/nerror` is included in package.json https://github.com/apache/cordova-common/blob/87167bd45670291b68e6e02852a6b4faf63ed247/package.json#L20

I suspect this might have something to do with there being a copy of cordova-common under `platforms/ios/cordova/node_modules` and maybe missing dependencies from there

**Comment by CodeWithOz** [comment]
@dpogue I'm just now experiencing this issue after upgrading to `cordova-cli@10`. The [npm page](https://www.npmjs.com/package/@netflix/nerror) for `@netflix/nerror` is not working for me, the npm site shoots out an `ESOCKETTIMEDOUT` error.

**Comment by breautek** [comment]
> @dpogue I'm just now experiencing this issue after upgrading to `cordova-cli@10`. The [npm page](https://www.npmjs.com/package/@netflix/nerror) for `@netflix/nerror` is not working for me, the npm site shoots out an `ESOCKETTIMEDOUT` error.

NPM is currently down. https://status.npmjs.org/

**Comment by CodeWithOz** [comment]
Ahh okay thanks :+1: .
