### ISSUE TITLE
getPreference broken in #133

### ISSUE THREAD

**Issue by RomanovX** [apache/cordova-common#172]
https://github.com/apache/cordova-common/blob/3c9b9ffb93e9ecdbf495a782bb2e5806d060b410/src/ConfigParser/ConfigParser.js#L161

By using `pop()` over the previous situation, only the last platform block is selected rather than all. This breaks various plugins that depend on this.

The change was introduced by #133.

**Comment by raphinesse** [comment]
Thanks for reporting this. So if I understand it correctly, the issue is the following:

Given following `config.xml`:
```xml
<platform name="android"></platform>

<platform name="android">
   <preference name="Fullscreen" value="true" />
</platform>
```

Pre #133 we would have
```js
config.getPlatformPreference('Fullscreen', 'android') === 'true'
```

and post #133 we would have
```js
config.getPlatformPreference('Fullscreen', 'android') === ''
```

Is that correct?

> This breaks various plugins that depend on this.

Would you mind giving some specific example?

**Comment by erisu** [comment]
There should only be one entry for a given platform. 

If what @raphinesse defined above is the case, I think you should merge the two elements together.

**Comment by breautek** [comment]
Closing as stale / no response.
