### ISSUE TITLE
Remove Platform Specific Code

### ISSUE THREAD

**Issue by erisu** [apache/cordova-common#36]
# Overview & Issue
Currently, cordova-common has platform-specific code which should reside in each platform repo. 

For example, when implementing the new API to support Android's Adaptive Icons, adding the necessary attributes to the icon element in `config.xml` is currently handled in common.

In a perfect world, common should only control the basic elements and attributes that are shared among all platforms.

# Goal
The goal of this ticket is to remove the platform-specific code from cordova-common and move them to their respective repo.

- This will involve converting the code into a base structure where each platform can extend each class. The platform will then inject its additional or modified logic.

- The platform-specific unit testing code will need to migrate to each respective repo.

- Remove the need to pass in platform type when the platform type is already known.

# Work in Progress
* https://github.com/erisu/cordova-common/tree/config-split
* https://github.com/erisu/cordova-ios/tree/config-split
* https://github.com/erisu/cordova-android/tree/config-split
* https://github.com/erisu/cordova-windows/tree/config-split

**Comment by janpio** [comment]
> ... that are shared among all platforms.

... that are - *common* *ba dum tss

**Comment by erisu** [comment]
# Latest CI Test Results
* [cordova-common](https://travis-ci.org/erisu/cordova-common/builds/432857644)
* [cordova-ios](https://travis-ci.org/erisu/cordova-ios/builds/432868146)
* [cordova-android](https://travis-ci.org/erisu/cordova-android/builds/432867036)
* [cordova-windows](https://travis-ci.org/erisu/cordova-windows/builds/432864386)
