### ISSUE TITLE
ConfigParser: Allow engines and plugins to be set in the format returned by get

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-common#39]
Specification by example:

```js
const cfg = new ConfigParser('...');

cfg.addEngine({
    name: 'atari',
    spec: '^0.4.2'
});

cfg.addPlugin({
    name: 'cordova-plugin-ice-cream',
    spec: '~0.2.3',
    variables: { foo: 'bar' }
});
```

It should be possible to implement this w/out breaking the current interface.

**Comment by dpogue** [comment]
We don't actually use `engine` and `plugin` tags now that those are handled with npm & package.json, so I'm going to close this. But it was a good suggestion at the time :)
