### ISSUE TITLE
Modify *.jsproj files with "config-file" element

### ISSUE THREAD

**Issue by holyhoehle** [apache/cordova-common#62]
Is there a reason why only XML files with the extensions .xml, .appxmanifest and .storyboard can be modified using the "config-file" element in the config.xml? I would like to modify the .jsproj, but it fails as it is trying to parse the file as a "plist" file.

https://github.com/apache/cordova-common/blob/193c9f3e2bf003292d12782f2d182a08c1b562b8/src/ConfigChanges/ConfigFile.js#L74

**Comment by janpio** [comment]
Some context here please. `.jsproj` of Cordova Windows? 
If that is a plain XML file, it is probably very possible to just add this extension here to make it work.

**Comment by holyhoehle** [comment]
Yes, I meant the `.jsproj` file of Cordova Windows. It is a simple XML file.
I was just wondering if there is a particular reason for not being able to modify it.

**Comment by janpio** [comment]
Probably no-one thought of it before or needed it. If you create a PR for common, I am sure we can get this merged and rolled out (sooner or later).
