### ISSUE TITLE
ConfigFIle.js for iOS Info.plist when the CocoaPods version is 1.6.* or later

### ISSUE THREAD

**Issue by knight9999** [apache/cordova-common#88]
# Bug Report

Image the `config.xml` or `plugin.xml` includes `config-file` tag like
```
      <config-file target="*-Info.plist" parent="SampleTest">
        <array>
          <string>hello</string>
        </array>
      </config-file> 
```

Then the `cordova-common` searches `[Application Name]-Info.plist` file under the `platform/ios` in order to update `[Application Name]-Info.plist` file in `cordova prepare` process.

This logic can be found in `src/ConfigChanges/ConfigFile.js` in `cordova-common` as

```
       // [CB-5989] multiple Info.plist files may exist. default to $PROJECT_NAME-Info.plist
        if (matches.length > 1 && file.includes('-Info.plist')) {
            var plistName = getIOSProjectname(project_dir) + '-Info.plist';
            for (var i = 0; i < matches.length; i++) {
                if (matches[i].includes(plistName)) {
                    filepath = matches[i];
                    break;
                }
            }
        }
```

This works well if the cocoapods version is 1.5.* or earlier.

However if the cocoapods version is 1.6.* or later, the project includes plugins which include cocoapods libraries with subdirectory path like `<pod name="Firebase/Core" spec="6.3.0"/>` , the file
```
  platforms/ios/Pods/Target Support Files/Pods-[Application Name]/Pods-[Application Name]-Info.plist
```
is created and this may lead wrong behavior in `config-file` tag with target `*-Info.plist` in `cordova prepare ios`.

This created file satisfies the above logic (i.e. finding `*-Info.plist` file) condition.

(Rematk that If the cocoapods version is 1.5.* or earlier, that file name is different. Actually the created file in this case is 

```
  platforms/ios/Pods/Target Support Files/Pods-[Application Name]/Info.plist
```
.  Therefore no problem happens)

## Problem

If the build environment uses CocoaPods 1.6.* or later and the project uses CocoaPods Library with subdirectory path structure like `<pod name="Firebase/Core" spec="6.3.0"/>`, 
There are two files which satisfies the above logic condition (i.e. `*-Info.plist` file finding condition) in config-file.  That two files' path are

```
platforms/ios/[Application Name]-Info.plist
platforms/ios/Pods/Target Support Files/Pods-[Application Name]/Info.plist
```

If the first letter of [Application Name] is `Q-Z` (i.e. the letter after `P` of `Pods`) , then the above logic detect the wrong file

```
 platforms/ios/Pods/Target Support Files/Pods-[Application Name]/Info.plist
```

instead of the correct file

```
platforms/ios/[Application Name]-Info.plist
```

as its `target file`.

### What is expected to happen?

Plugin's `config-file` with the target `*-Info.plist` must be applied to the correct one
```
platforms/ios/[Application Name]-Info.plist
```

### What does actually happen?

Plugin's `config-file` with the target `*-Info.plist` is applied to
```
platforms/ios/Pods/Target Support Files/Pods-[Application Name]/Info.plist
```

If all followings are satisfied,

i) cocoapods version is 1.6.* or later,
ii) some cocoapods libraries use subdirectory path structure. (like `cordova-plugin-firebasex` plugin. This plugin is different from `cordova-plugin-firebase`. )
iii) `config-file` tag in `config.xml` or `plugin.xml` changes `*-Info.plist` file.

### Command or Code

How to reproduce this iusse,

1. create cordova project
```
$ cordova create sampleProject
```

2. replace package.json
```
{
  "name": "helloworld",
  "displayName": "HelloCordova",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {
    "cordova-ios": "^5.0.1",
    "cordova-plugin-androidx": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.0",
    "cordova-plugin-firebasex": "^6.0.4"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-firebasex": {}
    },
    "platforms": [
      "ios"
    ]
  }
}
```

3. update config.xml

```
<widget ...>
    <name>Z-HelloCordova</name>
   ...
    <platform name="ios">
      <config-file target="*-Info.plist" parent="SampleTest">
        <array>
          <string>hello</string>
        </array>
      </config-file> 
      <allow-intent href="itms:*" />
      <allow-intent href="itms-apps:*" />
    </platform>     
```

4. do cordova prepare

```
$ cordova prepare ios
```

Then thare is no `SampleTest` in `platforms/ios/Z-HelloCordova/Z-HelloCordova-Info.plist`

However if we use the application name `A-HelloCordova`
```
    <name>A-HelloCordova</name>
```
in step2
, there is `SampleTest` in `platforms/ios/A-HelloCordova/A-HelloCordova-Info.plist` as

```
	<key>SampleTest</key>
	<array>
		<string>hello</string>
	</array>
```

### Environment, Platform, Device

Mac
ruby 2.3.7p456
CocoaPods 1.7.5
xcodebuild 10.3 (Build Version 10G8)
(Remark that this issue happens in `cordova prepare ios`)

### Version information
cordova-cli 9.0.0 (cordova-lib@9.0.1)
cordova-ios (in project node_modules) 5.0.1
cordova-common (in project node_modules) 3.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
One thing worth noting is that in newly-created Xcode projects, the plist filename is just `Info.plist` without the app name prefix. Unfortunately we can't rename ours to match without breaking every plugin.xml or config.xml that tries to edit it :confused:

**Comment by knight9999** [comment]
Thanks @dpogue .
I have just confirmed it by creating a new project by Xcode 10.3 with using a default ios `Single View App` template.

If we can't rename ours `[App Name]-Info.plist` filename in cordova-ios, 
I think we'd better update the logic to find `*-Info.plist` in `ConfigFile.js`.

**Comment by edwinofsakh** [comment]
I have a same problem. Is there a solution without changing the name of the application?

**Comment by codinronan** [comment]
@knight9999 damn... after 2 days of hunting the *specific* issue here is the bug in all its glory. Ran into this as well, actually ran through the entire alphabet to realize that any letter after 'P' was a problem and was totally stumped why that would be the case but I did realize that it had something to do with CocoaPods.

Ok so now that knight has done all the hard work of figuring out why it happens here's the solution:

```
diff --git a/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js b/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js
index be8f78e..20340fe 100644
--- a/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js
+++ b/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js 
@@ -175,7 +175,7 @@ function resolveConfigFilePath (project_dir, platform, file) {
 
         // [CB-5989] multiple Info.plist files may exist. default to $PROJECT_NAME-Info.plist
         if (matches.length > 1 && file.includes('-Info.plist')) {
-            var plistName = getIOSProjectname(project_dir) + '-Info.plist';
+            var plistName = '/' + getIOSProjectname(project_dir) + '-Info.plist';
             for (var i = 0; i < matches.length; i++) {
                 if (matches[i].includes(plistName)) {
                     filepath = matches[i];
```

Just throw that change into patch-package and you are golden. This change ensures that the only matching filename MUST begin with the forward slash (which excludes any Pods path) without accidentally excluding app names that might start with the word "Pods".

I'd open a PR for this but... I've actually spent 5 days hunting this down (it started when I realized none of the plugins had any of their variables). Time to catch up on lost time.

**Comment by knight9999** [comment]
@codinronan Thanks for great work. Please open your PR!

**Comment by Armanio** [comment]
@codinronan, @knight9999 thx for yours effort. 🥇
